services:
  app:
    build:
      context: .

      args:
        - DEV=true
    ports:
      - "8010:8010"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web

    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8010"


       environment:
       - DB_HOST=db
       - DB_NAME=devdb
       - DB_USER=devusern
       - DB_PASS=changeii9o
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devusern
      - POSTGRES_PASSWORD=changeii9o
    ports:
      - "5433:5432"
volumes:
  dev-db-data:
  dev-static-data:
